language: python
python:
        - "3.4"
before_install:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
install:
        - "pip install -r requirements.txt"
script:
        - "python manage.py test"
        - "python manage.py runserver &"
        - "python functional_test.py"
