language: python
python:
        - "3.4"
before_install:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
install:
        - "pip install selenium"
script:
        - "python functional_test.py"
